<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'App\\Domain\\User\\UserRepository' => 'get1',
  'Psr\\Log\\LoggerInterface' => 'get2',
  'settings' => 'get3',
  'subEntry1' => 'get4',
);

    protected function get1()
    {
        $object = new App\Infrastructure\Persistence\User\InMemoryUserRepository(NULL);
        return $object;
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            $settings = $c->get('settings');

            $loggerSettings = $settings['logger'];
            $logger = new \Monolog\Logger($loggerSettings['name']);

            $processor = new \Monolog\Processor\UidProcessor();
            $logger->pushProcessor($processor);

            $handler = new \Monolog\Handler\StreamHandler($loggerSettings['path'], $loggerSettings['level']);
            $logger->pushHandler($handler);

            return $logger;
        }, 'Psr\\Log\\LoggerInterface');
    }

    protected function get4()
    {
        return [
            'name' => 'slim-app',
            'path' => 'E:\\cs090\\slimCMS\\app/../logs/app.log',
            'level' => 100,
        ];
    }

    protected function get3()
    {
        return [
            'displayErrorDetails' => true,
            'logger' => $this->get4(),
        ];
    }

}
